version: "3.12"

services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/ProjectHabitTracker
      - static_volume:/ProjectHabitTracker/static
      - media_volume:/ProjectHabitTracker/media
    ports:
      - "8080:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env



  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${NAME} -U ${USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/drf-spa
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/drf-spa
    env_file:
      - .env
    depends_on:
      - db
      - redis

  backend:
    build: .
    command: bash -c "python manage.py migrate && python manage.py collectstatic -c --no-input && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      REDIS_URL: "redis://localhost:6379"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - django_static:/app/static/

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - django_static:/app/static/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/ProjectHabitTracker/static
    depends_on:
      backend:
        condition: service_started

networks:
  default:

volumes:
  postgres_data:
  static_volume:
  redis_data:
  media_volume:
  django_static:

